TaskManager/basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Person;
use app\models\Task;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionAddtaskform()
    {
		if(!Yii::$app->user->isGuest)
		{
			$query = Person::find();
			$persons = $query->all();	
			$access = "1";
		}	
		else $access = "0";
        return $this->renderAjax('addtaskajax', [
            'persons' => $persons, 
            'access' => $access,          
        ]);		   	
	}      
    public function actionEdittaskform()
    {
		if(isset($_POST['edit_task_id'])&&!Yii::$app->user->isGuest)
		{
			$task_id = $_POST['edit_task_id'];
			$task = Task::findOne($task_id);
			$task_user = $task->user;
			$task_title = $task->title;
			$task_status = $task->status;		
			$task_description = $task->description;	
			$params = array($task_id,$task_user,$task_title,$task_status,$task_description);
			$query = Person::find();
			$persons = $query->all();
			$access = "1";				
		}	
		else $access = "0";
        return $this->renderAjax('edittaskajax', [
            'params' => $params,
            'persons' => $persons,
            'access' => $access,         
        ]);		   	
	} 
    public function actionAddpersonform()
    {
		if(!Yii::$app->user->isGuest)
		{
			$access = "1";	
		}	
		else $access = "0";
        return $this->renderAjax('addpersonajax', [
            'access' => $access,          
        ]);		   	
	} 	
    public function actionEditpersonform()
    {
		if(isset($_POST['edit_person_id'])&&!Yii::$app->user->isGuest) {
			$person_id = $_POST['edit_person_id'];
			$person = Person::findOne($person_id);
			$person_name = $person->name;
			$person_occupation = $person->occupation;	
			$params = array($person_id,$person_name,$person_occupation);
			$access = "1";					
		}	
		else $access = "0";
        return $this->renderAjax('editpersonajax', [
            'params' => $params,    
            'access' => $access,      
        ]);		   	
	}	
    public function actionAddtask()
    {
		if(isset($_POST)&&!Yii::$app->user->isGuest)
		{
			$i = 0;	
			$elements = [];		
			foreach ($_POST as $element) {
				$elements[$i] = $element;
				$i++;
			}			
			$user = $elements[0];
			$title = $elements[1];
			$status = $elements[2];
			$description = $elements[3];
			$task = new Task;	
			$task->user = $user;
			$task->title = $title;			
			$task->status = $status;
			$task->description = $description;	
			$result = $task->save();
			if ($result) 
			{
				$out_arr = array('id' => $task->id, 'title' => $title, 'user' => $user, 'status' => $status, 'description' => $description, 'message' => 'added');				
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);
        return $output;         		   	
	} 	
    public function actionEdittask()
    {
		if(isset($_POST)&&!Yii::$app->user->isGuest)
		{
			$i = 0;	
			$elements = [];		
			foreach ($_POST as $element) {
				$elements[$i] = $element;
				$i++;
			}			
			$id = $elements[0];
			$title = $elements[2];
			$user = $elements[1];
			$status = $elements[3];
			$description = $elements[4];
			$task = Task::findOne($id);	
			$task->title = $title;
			$task->user = $user;
			$task->status = $status;
			$task->description = $description;	
			$result = $task->save();
			if ($result) 
			{
				$out_arr = array('id' => $id, 'title' => $title, 'user' => $user, 'status' => $status, 'description' => $description, 'message' => 'updated');				
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);        
            
        return $output;      		   	
	} 
    public function actionDeletetask()
    {
		if(isset($_POST['delete_task_id'])&&!Yii::$app->user->isGuest)
		{		
			$id = $_POST['delete_task_id']; 	
			$task = Task::findOne($id);
			$title = $task->title;
			$user = $task->user;
			$status = $task->status;
			$description = $task->description;						
			$result = $task->delete();
			if ($result) 
			{
				$out_arr = array('id' => $id, 'title' => $title, 'user' => $user, 'status' => $status, 'description' => $description, 'message' => 'deleted');				
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);
        return $output;         		   	
	} 	
    public function actionAddperson()
    {
		if(isset($_POST)&&!Yii::$app->user->isGuest)
		{
			$i = 0;	
			$elements = [];		
			foreach ($_POST as $element) {
				$elements[$i] = $element;
				$i++;
			}			
			$name = $elements[0];
			$occupation = $elements[1];
			$person = new Person;	
			$person->name = $name;
			$person->occupation = $occupation;				
			$result = $person->save();
			if ($result) 
			{
				$out_arr = array('id' => $person->id, 'name' => $name, 'occupation' => $occupation, 'message' => 'added');				
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);
        return $output;         		   	
	}		
    public function actionEditperson()
    {
		if(isset($_POST)&&!Yii::$app->user->isGuest)
		{
			$i = 0;	
			$elements = [];		
			foreach ($_POST as $element) {
				$elements[$i] = $element;
				$i++;
			}			
			$id = $elements[0];
			$name = $elements[1];
			$occupation = $elements[2];
			$person = Person::findOne($id);	
			$person->name = $name;
			$person->occupation = $occupation;
			$result = $person->save();
			
			if ($result) 
			{
				$out_arr = array('id' => $id, 'name' => $name, 'occupation' => $occupation, 'message' => 'updated');				
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);
        return $output;         		   	
	}
    public function actionDeleteperson()
    {
		if(isset($_POST['delete_person_id'])&&!Yii::$app->user->isGuest)
		{			
			$id = $_POST['delete_person_id'];
			$person = Person::findOne($id);
			$name = $person->name;
			$occupation = $person->occupation;					
			$result = $person->delete();
			if ($result) 
			{
				$out_arr = array('id' => $id, 'name' => $name, 'occupation' => $occupation, 'message' => 'deleted');			
			}	
			else $out_arr = array('message' => 'error');				
		}	
		else $out_arr = array('message' => 'access denied');
		$output = json_encode($out_arr);
        return $output;         		   	
	} 	 	    
    public function actionIndex()
    {
		$query = Person::find();
		$query_tasks = Task::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);
         $pagination_tasks = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query_tasks->count(),
        ]);       

        $persons = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        $tasks = $query_tasks->orderBy('user')
            ->offset($pagination_tasks->offset)
            ->limit($pagination_tasks->limit)
            ->all();         
            
        return $this->render('index', [
            'persons' => $persons,
            'tasks' => $tasks,
            'pagination' => $pagination,
            'pagination_tasks' => $pagination_tasks,           
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */

TaskManager/basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

TaskManager/basic/views/site/addpersonajax.php
<?php 
use yii\helpers\Url;
?>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.css" rel="stylesheet">
<?php if($access=="1") {?>
<form id="add_person_form" action="/">
	<p>Add new user</p>
	<p>Name</p>
	<input type="text" name="name">		
	<p style="margin-top:5px;">Occupation</p>
	<input type="text" name="Occupation">		
	<button type="submit" name="action" value="1">Add</button>
</form>

<script type="text/javascript">
	$( "#add_person_form" ).submit(function( event ) {
		  var $form = $(this);
		  $.ajax({
			type: 'POST',
			url: '<?php echo Url::to(['site/addperson']) ?>',
			update: '#newform',
			data: $form.serialize(),
			success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', name:'+json_data.name+', occupation:'+json_data.occupation+', status:'+json_data.status+', message:'+json_data.message,
					color: 'blue'
				});	
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
                $( "#user_table" ).append("<tr id=ptr"+json_data.id+"><td>"+json_data.name+"</td><td>"+json_data.occupation+"</td><td><button type=button onclick=edit_person_form("+json_data.id+");>Edit</button></td><td><button type=button onclick=delete_person("+json_data.id+");>Delete</button></td></tr>" );
			},
			error:function(data){
                alert(data[0]); 
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
			},			
		  });
		event.preventDefault();
	});
</script>

<?php } else echo'<p>access denied</p>';?>

TaskManager/basic/views/site/addtaskajax.php
<?php 
use yii\helpers\Url;
?>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.css" rel="stylesheet">
<?php if($access=="1") {?>
<form id="add_task_form" action="/">
	<p>Add new task</p>
	<p>User</p>
	<select name="user">	
		<?php 
		foreach ($persons as $person) {
			echo '<option value="'.$person->name.'">'.$person->name.'</option>';
		}
		?>
	</select>		
	<p style="margin-top:5px;">Title</p>
	<input type="text" name="title">		
	<p style="margin-top:5px;">Status</p>
	<input type="text" name="status">	
	<p style="margin-top:5px;">Description</p>
	<input type="text" name="description"> 
	<button type="submit" name="action" value="1">Add</button>
</form>

<script type="text/javascript">
	$( "#add_task_form" ).submit(function( event ) {
		  var $form = $(this);
		  $.ajax({
			type: 'POST',
			url: '<?php echo Url::to(['site/addtask']) ?>',
			update: '#newform',
			data: $form.serialize(),
			success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', title:'+json_data.title+', user:'+json_data.user+', status:'+json_data.status+', description:'+json_data.description+', message:'+json_data.message,
					color: 'blue'
				});	
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
                $( "#task_table" ).append("<tr id=tr"+json_data.id+"><td>"+json_data.title+"</td><td>"+json_data.user+"</td><td>"+json_data.status+"</td><td>"+json_data.description+"</td><td><button type=button onclick=edit_task_form("+json_data.id+");>Edit</button></td><td><button type=button onclick=delete_task("+json_data.id+");>Delete</button></td></tr>" );
			},
			error:function(data){
                alert(data[0]); 
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
			},			
		  });
		event.preventDefault();
	});
</script>

<?php } else echo'<p>access denied</p>';?>

TaskManager/basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

TaskManager/basic/views/site/editpersonajax.php
<?php 
use yii\helpers\Url;
?>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.css" rel="stylesheet">
<?php if($access=="1") {?>
<form id="edit_person_form" action="/">
	<input type="hidden" name="id" value="<?php echo $params[0];?>">
	<p>Edit user <?php echo $params[1];?></p>	
	<p>Name</p>
	<input type="text" name="title" value="<?php echo $params[1];?>">		
	<p style="margin-top:5px;">Occupation</p>
	<input type="text" name="status" value="<?php echo $params[2];?>">	
	<button type="submit" name="action" value="1">Save</button>
</form>

<script type="text/javascript">
	$( "#edit_person_form" ).submit(function( event ) {
		  var $form = $(this);
		  $.ajax({
			type: 'POST',
			url: '<?php echo Url::to(['site/editperson']) ?>',
			update: '#newform',
			data: $form.serialize(),
			success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', name:'+json_data.name+', occupation:'+json_data.occupation+', status:'+json_data.status+', message:'+json_data.message,
					color: 'blue'
				});
                $('#newform').html(''); 
                $(".body-content").css("display","block");  
                $('#ptr'+json_data.id).replaceWith("<tr id=ptr"+json_data.id+"><td>"+json_data.name+"</td><td>"+json_data.occupation+"</td><td><button type=button onclick=edit_person_form("+json_data.id+");>Edit</button></td><td><button type=button onclick=delete_person("+json_data.id+");>Delete</button></td></tr>" );
			},
			error:function(data){
                alert(data[0]); 
				document.location.reload(true);
			},			
		  });
		event.preventDefault();
	});
</script>

<?php } else echo'<p>access denied</p>';?>

TaskManager/basic/views/site/edittaskajax.php
<?php 
use yii\helpers\Url;
?>
<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.css" rel="stylesheet">
<?php if($access=="1") {?>
<form id="edit_task_form" action="/">
	<input type="hidden" name="id" value="<?php echo $params[0];?>">
	<p>Edit task for user <?php echo $params[1];?></p>	
	<p>Change user</p>
	<select name="user">	
		<?php 
		foreach ($persons as $person) {
			?><option value="<?php echo $person->name;?>" <?php if($person->name==$params[1]) echo 'selected';?>><?php echo $person->name;?></option><?php
		}
		?>
	</select>	
	<p style="margin-top:5px;">Title</p>
	<input type="text" name="title" value="<?php echo $params[2];?>">		
	<p style="margin-top:5px;">Status</p>
	<input type="text" name="status" value="<?php echo $params[3];?>">	
	<p style="margin-top:5px;">Description</p>
	<input type="text" name="description" value="<?php echo $params[4];?>"> 
	<button type="submit" name="action" value="1">Save</button>
</form>

<script type="text/javascript">
	$( "#edit_task_form" ).submit(function( event ) {
		  var $form = $(this);
		  $.ajax({
			type: 'POST',
			url: '<?php echo Url::to(['site/edittask']) ?>',
			update: '#newform',
			data: $form.serialize(),
			success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', title:'+json_data.title+', user:'+json_data.user+', status:'+json_data.status+', description:'+json_data.description+', message:'+json_data.message,
					color: 'blue'
				});
                $('#newform').html(''); 
                $(".body-content").css("display","block");  
                $('#tr'+json_data.id).replaceWith("<tr id=tr"+json_data.id+"><td>"+json_data.title+"</td><td>"+json_data.user+"</td><td>"+json_data.status+"</td><td>"+json_data.description+"</td><td><button type=button onclick=edit_task_form("+json_data.id+");>Edit</button></td><td><button type=button onclick=delete_task("+json_data.id+");>Delete</button></td></tr>" );              
			},
			error:function(data){
				alert(data[0]);
                $('#newform').html(''); 
                $(".body-content").css("display","block");                 
			},			
		  });
		event.preventDefault();
	});
</script>

<?php } else echo'<p>access denied</p>';?>

TaskManager/basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

TaskManager/basic/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$this->title = 'Task manager';
?>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.js"></script>
<link href="https://cdn.jsdelivr.net/gh/StephanWagner/jBox@v0.6.4/dist/jBox.all.min.css" rel="stylesheet">
<div class="site-index">

    <h1>Task manager</h1>

    <p class="lead">Tables with users and their tasks</p>

    <div class="body-content">
		<?= yii\bootstrap4\Tabs::widget(['items' => [
          [
              'label' => 'Tasks',
              'content' => $this->render('tasks', ['tasks' =>$tasks, 'pagination_tasks' => $pagination_tasks]),
              'active' => true
          ],
          [
              'label' => 'Users',
              'content' => $this->render('workers', ['persons' =>$persons, 'pagination' => $pagination]),
          ],
         ]]) ?>                          
    </div>
    
<div id="newform"></div>

<script type="text/javascript">
	
function add_task_form()
 {

  $.ajax({
   type: 'POST',
   url: '<?php echo Url::to(['site/addtaskform']) ?>',
   update: '#newform',
   dataType:'html',
   success:function(data){
                $('#newform').html(data); 
                $(".body-content").css("display","none");
   },
   error:function(data){
                alert("error");
   },   
  }); 
}
	
function edit_task_form(data)
 {

  $.ajax({
   type: 'POST',
   url: '<?php echo Url::to(['site/edittaskform']) ?>',
   update: '#newform',
   data:{edit_task_id:data},
   dataType:'html',
   success:function(data){
                $('#newform').html(data); 
                $(".body-content").css("display","none");
   },
   error:function(data){
                alert("error");
   },   
  }); 
}

function delete_task(data)
 {

  $.ajax({
   type: 'POST',
    url: '<?php echo Url::to(['site/deletetask']) ?>',
   data:{delete_task_id:data},
   dataType:'html',
   success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', title:'+json_data.title+', user:'+json_data.user+', status:'+json_data.status+', description:'+json_data.description+', message:'+json_data.message,
					color: 'blue'
				});				
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
                $('#tr'+json_data.id).remove();
   },
   error:function(data){
                alert("error");
   },   
  }); 
}

function add_person_form()
 {

  $.ajax({
   type: 'POST',
   url: '<?php echo Url::to(['site/addpersonform']) ?>',
   update: '#newform',
   dataType:'html',
   success:function(data){
                $('#newform').html(data); 
                $(".body-content").css("display","none");
   },
   error:function(data){
                alert("error");
   },   
  }); 
}

function edit_person_form(data)
 {

  $.ajax({
   type: 'POST',
   url: '<?php echo Url::to(['site/editpersonform']) ?>',
   update: '#newform',
   data:{edit_person_id:data},
   dataType:'html',
   success:function(data){
                $('#newform').html(data); 
                $(".body-content").css("display","none");
   },
   error:function(data){
                alert("error");
   },   
  });

}

function delete_person(data)
 {

  $.ajax({
   type: 'POST',
    url: '<?php echo Url::to(['site/deleteperson']) ?>',
   data:{delete_person_id:data},
   dataType:'html',
   success:function(data){
				var json_data = jQuery.parseJSON(data);
				new jBox('Notice', {
					offset: {
						y: 50
					},
					content: 'id:'+json_data.id+', name:'+json_data.name+', occupation:'+json_data.occupation+', message:'+json_data.message,
					color: 'blue'
				});								
                $('#newform').html(''); 
                $(".body-content").css("display","block"); 
                $('#ptr'+json_data.id).remove();
   },
   error:function(data){
                alert("error");
   },   
  }); 
}

</script>    
    
</div>

TaskManager/basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>